src/cdic_project/cdic/forms/copr.py
# coding: utf-8

from flask_wtf import Form
from wtforms import StringField, ValidationError


class CoprSearchLinkForm(Form):
    query = StringField(label="Search for copr projects")


class CoprNameValidator(object):
    def __init__(self, message=None):
        if not message:
            message = "Wrong format for copr name: '{}'"
        self.message = message

    def __call__(self, form, field):
        try:
            user, copr = field.data.split("/")
            if not user:
                raise ValidationError("Missing copr username")
            if not copr:
                raise ValidationError("Missing copr projectname")
        except ValueError:
            raise ValidationError(self.message.format(field.data))


class CoprLinkAddForm(Form):
    copr_name = StringField(label="Enter copr in the format `copr_owner/copr_project`",
                            validators=[CoprNameValidator()])

src/cdic_project/cdic/__init__.py
# coding: utf-8

import os
import sys
import logging
from flask import Flask, jsonify, render_template, url_for
import flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from sqlalchemy.orm.exc import NoResultFound
from werkzeug.utils import redirect

from .exceptions import AccessRejected
from .util.git import GitStore
from .util.dockerhub import DhConnector

app = Flask(__name__)

# oid = OpenID(app, app.config["OPENID_STORE"], safe_roots=[])
app.config.from_pyfile("../config.py")
app.config.from_pyfile("/etc/cdic/cdic_db.py", silent=True)
app.config.from_pyfile(os.path.expanduser("~/.config/cdic.py"), silent=True)

log = logging.getLogger(__name__)

Bootstrap(app)

git_store = GitStore(app.config["CDIC_WORKPLACE"])

db = SQLAlchemy()
db.init_app(app)

dh_connector = DhConnector(app.config)
""":type:cdic_project.cdic.util.DhConnector"""

from .filters import time_ago

from .views.main import main_bp
from .views.auth import auth_bp
from .views.project import project_bp

app.register_blueprint(main_bp)
app.register_blueprint(auth_bp)
app.register_blueprint(project_bp)


@app.route('/api/help', methods=['GET'])
def help_urls():
    """Print available functions."""
    func_list = {}
    for rule in app.url_map.iter_rules():
        if rule.endpoint != 'static':
            func_list[rule.rule] = app.view_functions[rule.endpoint].__doc__
    return jsonify(func_list)


@app.errorhandler(NoResultFound)
def page_not_found(error):
    flask.flash("requested page not found: {}".format(flask.request.path), "danger")
    return redirect(url_for("main.index"))


@app.errorhandler(404)
def page_not_found(error):
    flask.flash("requested page not found: {}".format(flask.request.path), "danger")
    return redirect(url_for("main.index"))


if __name__ == "__main__":
    logging.basicConfig(
        filename=app.config["MAIN_LOG"],
        format='[%(asctime)s][%(threadName)10s][%(levelname)6s][%(name)s]: %(message)s',
        level=logging.DEBUG
    )


@app.errorhandler(AccessRejected)
def access_rejected_handler(error):
    flask.flash(str(error), "danger")
    return redirect(url_for("main.index"))

src/cdic_project/cdic/views/auth.py
# coding: utf-8

import base64
import datetime
import functools
import re

import flask
from flask import g, session, redirect, flash, url_for, request

from flask_openid import OpenID

from .. import app, db
from ..models import User

auth_bp = flask.Blueprint("auth", __name__, url_prefix="/auth")
oid = OpenID(app, app.config["OPENID_STORE"], safe_roots=[])


class FasOID(object):
    uri = "https://id.fedoraproject.org/"
    oid_pre = "http://"
    oid_suf = ".id.fedoraproject.org/"

    @classmethod
    def from_username(cls, name):
        return "{}{}{}".format(cls.oid_pre, name, cls.oid_suf)

    @classmethod
    def to_raw_name(cls, fas_name):
        """
        Extracts name from FAS openId identifier
        :param str fas_name: FAS user openId
        :return str: user raw name
        """
        if fas_name.startswith(cls.oid_pre) and fas_name.endswith(cls.oid_suf):
            return fas_name.replace(cls.oid_pre, "").replace(cls.oid_suf, "")
        else:
            raise Exception("Malformed fas name: `{}`".format(fas_name))


@app.before_request
def lookup_current_user():
    g.user = None
    if 'openid' in session:
        username = FasOID.to_raw_name(session['openid'])
        g.user = User.query.filter_by(username=username).first()


@auth_bp.route('/login', methods=['GET', 'POST'])
@oid.loginhandler
def login():
    if g.user is not None:
        session["openid_attempts"] = 0
        print("\n\n\n LOGGED IN \n\n\n\n")
        return redirect(oid.get_next_url())
    else:
        openid_attempts_count = session.get("openid_attempts", 0)
        if openid_attempts_count > 300:
            raise Exception("OpenID auth failed to much times")
        else:
            session["openid_attempts"] = openid_attempts_count + 1
            return oid.try_login(FasOID.uri,
                                 ask_for=['email', 'timezone'],)


@oid.after_login
def create_or_login(resp):
    session['openid'] = resp.identity_url
    username = FasOID.to_raw_name(resp.identity_url)
    user = User.query.filter_by(username=username).first()
    if user is not None:
        flash(u'Successfully signed in', "success")
        g.user = user
    else:

        # ToDo: create auth_logic and move it there
        user = User(
            username=username,
            mail=resp.email,
            timezone=resp.timezone)
        db.session.add(user)
        db.session.commit()

    return redirect(oid.get_next_url())


@auth_bp.route("/logout/")
def logout():
    flask.session.pop("openid", None)
    flask.flash(u"You were signed out", "success")
    return flask.redirect(oid.get_next_url())


def login_required(f):
    @functools.wraps(f)
    def decorated_function(*args, **kwargs):
        if g.user is None:
            return redirect(url_for("auth.login", next=request.url))

        return f(*args, **kwargs)
    return decorated_function

src/cdic_project/cdic/views/main.py
# coding: utf-8

from flask import Blueprint, render_template
# from werkzeug import check_password_hash, generate_password_hash

import logging
log = logging.getLogger(__name__)

from ..logic.project_logic import ProjectLogic

main_bp = Blueprint("main", __name__)


@main_bp.route("/")
def index():
    return render_template(
        "index.html",
        project_list=ProjectLogic.query_all_ready_projects().limit(20),
        home_btn_active=True)

src/cdic_project/cdic/views/project.py
# coding: utf-8
import datetime
import json
import logging
import flask
from werkzeug.utils import redirect


# from app.views.copr import log
from ..action import run_build_async, delete_projects_task, create_project_repos_task

log = logging.getLogger(__name__)

from sqlalchemy.orm.exc import NoResultFound
from flask import Blueprint, request, abort, render_template, flash, g, redirect, url_for

from .. import db, app
from ..models import Project
from ..exceptions import CoprSearchError
from ..forms.copr import CoprSearchLinkForm, CoprLinkAddForm

from ..views.auth import login_required
from ..logic.copr_logic import get_link_by_id, create_link, check_link_exists
from ..logic.user_logic import get_user_by_name
# from ..actions.build import schedule_build
from ..async.pusher import schedule_task_async
from ..logic.project_logic import ProjectLogic
from ..logic.event_logic import create_project_event
from ..util.copr import search_coprs, check_copr_existence
from ..forms.project import ProjectForm, ProjectCreateForm, delete_form_factory
from ..constants import EventType


project_bp = Blueprint("project", __name__)


@project_bp.route("/u/<username>/")
def list_by_user(username):
    try:
        owner = get_user_by_name(username)

        return render_template(
            "project/list.html",
            owner=owner,
            my_prj_btn_active=True,
            project_list=ProjectLogic.query_by_owner(username)
        )

    except NoResultFound:
        abort(404)


@project_bp.route("/projects/<project_id>/")
def details_by_id(project_id):
    project = ProjectLogic.get_project_by_id(int(project_id))
    return redirect(url_for("project.details", username=project.user.username, title=project.title))


@project_bp.route("/u/<username>/p/<title>/")
def details(username, title):
    user = get_user_by_name(username)
    project = ProjectLogic.get_project_by_title(user, title)
    return render_template("project/details.html", project=project, project_info_page=True)


@project_bp.route("/p/add", methods=["GET"])
@login_required
def create_view(form=None):
    form = form or ProjectCreateForm()
    return render_template("project/add.html", form=form)


@project_bp.route("/p/add", methods=["POST"])
@login_required
def create_handle():
    form = ProjectCreateForm()
    if form.validate_on_submit():
        if ProjectLogic.exists_for_user(g.user, form.title.data):
            abort(400)
            # todo: replace with exception raise
        else:
            project = Project(
                user=g.user,
                title=form.title.data,
                source_mode=form.source_mode.data,
            )

            project.local_text = "FROM fedora:latest \n"
            project.patched_dockerfile = ""
            event = create_project_event(project, "Created")
            db.session.add_all([project, event])
            db.session.commit()
            schedule_task_async(create_project_repos_task, project.id)
            return redirect(url_for("project.details", username=project.user.username, title=project.title))
    else:
        return create_view(form=form)


@project_bp.route("/u/<username>/p/<title>/init_repos", methods=["GET", "POST"])
@login_required
def init_repos(username, title):
    user = get_user_by_name(username)
    project = ProjectLogic.get_project_by_title(user, title)

    project.check_editable_by(g.user)

    schedule_task_async(create_project_repos_task, project.id)

    flash("Repo creation scheduled", "success")
    return redirect(url_for("project.details", username=project.user.username, title=project.title))


@project_bp.route("/u/<username>/p/<title>/start_build", methods=["GET", "POST"])
@login_required
def start_build(username, title):
    user = get_user_by_name(username)
    project = ProjectLogic.get_project_by_title(user, title)

    project.check_editable_by(g.user)
    # if project.build_is_running:
    #     flash("Build request is already being processed, please wait", "danger")
    #     return redirect(url_for("project.details", username=project.user.username, title=project.title))

    # schedule_build(project)
    run_build_async(project)
    flash("Build scheduled", "success")
    return redirect(url_for("project.details", username=project.user.username, title=project.title))


@project_bp.route("/u/<username>/p/<title>/edit", methods=["GET", "POST"])
@login_required
def edit(username, title):
    user = get_user_by_name(username)
    project = ProjectLogic.get_project_by_title(user, title)

    form = ProjectForm(obj=project)

    if request.method == "POST" and form.validate_on_submit():
        old_source_mode = project.source_mode

        project.local_text = form.local_text.data
        project.git_url = form.git_url.data

        event = create_project_event(project, "Edited",
                                     data_json=json.dumps(form.data),
                                     event_type=EventType.PROJECT_EDITED)
        ProjectLogic.update_patched_dockerfile(project)
        db.session.add_all([project, event])
        db.session.commit()
        flash("Project was altered", "success")

        if old_source_mode == project.source_mode:
            # if not user should source fields
            return redirect(url_for("project.details", username=project.user.username, title=project.title))

    return render_template("project/edit.html", project=project, form=form, project_edit_page=True)


@project_bp.route("/users/<username>/<title>/delete", methods=["GET", "POST"])
@login_required
def delete(username, title):
    user = get_user_by_name(username)
    project = ProjectLogic.get_project_by_title(user, title)

    form = delete_form_factory(project)
    if request.method == "POST" and form.validate_on_submit():

        project.delete_requested_on = datetime.datetime.utcnow()
        ev = create_project_event(project, "Delete requested",
                                  event_type=EventType.DELETE_REQUESTED)
        db.session.add_all([project, ev])
        db.session.commit()
        schedule_task_async(delete_projects_task, project.id)

    return render_template("project/delete.html", project=project,
                           form=form, project_delete_page=True)


@project_bp.route("/users/<username>/<title>/link_coprs/", methods=["GET", "POST"])
@login_required
def search_and_link(username, title):
    user = get_user_by_name(username)
    project = ProjectLogic.get_project_by_title(user, title)

    form_search = CoprSearchLinkForm()
    form_add = CoprLinkAddForm()

    kwargs = {}
    # import ipdb; ipdb.set_trace()

    def try_add(copr_username, copr_projectname) -> bool:
        """
        :return: True on success
        """
        if check_link_exists(project, copr_username, copr_projectname):
            flask.flash("Copr '{}/{}' is already linked, probably you want to link another one?"
                        .format(copr_username, copr_projectname), category="error")
            return False
        elif not check_copr_existence(copr_username, copr_projectname):
            flask.flash("There are no such  project '{}/{}' at {}"
                        .format(copr_username, copr_projectname, app.config["COPR_BASE_URL"]),
                        category="error")
            return False
        else:
            copr_link = create_link(project, copr_username, copr_projectname)
            db.session.commit()
            flask.flash("Copr {} was linked to {}"
                        .format(copr_link.full_name, project.repo_name),
                        category="success")
        return True

    if request.form.get("btn") == "add_by_name":
        if form_add.validate_on_submit():
            copr_username, copr_projectname = form_add.copr_name.data.split("/")
            if try_add(copr_username, copr_projectname):
                return redirect(url_for("project.search_and_link",
                                        username=username, title=title))

    elif request.form.get("btn") == "search" or "btn-search-add" in request.form:
        if form_search.validate_on_submit():
            query = form_search.query.data
            try:
                kwargs["search_results"] = search_coprs(query)
            except CoprSearchError as err:
                kwargs["search_results"] = []
                kwargs["search_error"] = str(err)

        if "btn-search-add" in request.form:
            # we hope that this value was generated by our self,
            # in worst case can cause 500 error

            copr_username, copr_projectname = request.form["btn-search-add"].split("/")
            try_add(copr_username, copr_projectname)

    kwargs["form_add"] = form_add
    kwargs["form_search"] = form_search
    kwargs["project"] = project
    kwargs["project_link_page"] = True

    return render_template("project/find_and_link_coprs.html", **kwargs)


@project_bp.route("/users/<username>/<title>/link_coprs/<link_id>/delete")
@login_required
def unlink(username, title, link_id):
    user = get_user_by_name(username)
    project = ProjectLogic.get_project_by_title(user, title)
    link = get_link_by_id(link_id)
    if link and link in project.linked_coprs:
        ProjectLogic.update_patched_dockerfile(project)
        event = create_project_event(
            link.project,
            "Removed linked copr: {}/{}".format(link.username, link.coprname),
            data_json=json.dumps({"id": link.id, "username": link.username, "coprname": link.coprname}),
            event_type="removed_link")
        db.session.add_all([project, event])
        db.session.delete(link)
        db.session.commit()
        flask.flash("Copr {} was unlinked from {}"
                    .format(link.full_name, project.repo_name),
                    category="success")
    return redirect(url_for("project.search_and_link",
                            username=project.user.username, title=project.title))

src/cdic_project/cdic/templates/project/add.html
{% extends "base.html" %}

{% block inner_content %}
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li>
      <a href="{{ url_for('project.list_by_user',username=g.user.username) }}">
        {{ g.user.username }}
      </a>
    </li>
    <li class="active">Creating project</li>
  </ol>
  <h1 class="text-center"> Create new project </h1>

  <form class="form form-horizontal" method="post" role="form">
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    {{ wtf.form_field(form.title) }}

    <!--<div class="form-group ">-->
      <!--<label class="control-label" for="source_mode">-->
        <!--Select source mode for project-->
      <!--</label>-->
      <!--{{ wtf.form_field(form.source_mode) }}-->
    <!--</div>-->
    <!---->

     <button type="submit" class="btn btn-primary">Submit</button>
  </form>


{% endblock %}

src/cdic_project/cdic/templates/project/base.html
{% extends "base.html" %}


<!-- for Dockerfile highlighting -->
{% block styles %}
  {{super()}}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/styles/default.min.css">
{% endblock %}

{% block scripts %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/highlight.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/languages/dockerfile.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  {{super()}}
{% endblock %}




{% block inner_content %}

  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li>
      <a href="{{ url_for('project.list_by_user',username=project.user.username) }}">
        {{ project.user.username }}
      </a>
    </li>
    <li><a href="{{ url_for('project.details', username=project.user.username, title=project.title) }}">
      {{ project.title }}
    </a></li>
    {% block last_breadcrumb %}{% endblock %}

  </ol>

  <h1 class="text-left">Project: {{ project.title }}</h1>
  <ul class="nav nav-pills">
    <li role="presentation" class="{% if project_info_page %} active {% endif %}">
      <a class="btn btn-default"
         href="{{ url_for('project.details', username=project.user.username, title=project.title) }}">
        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
        Info
      </a>
    </li>
    {% if g.user == project.user and project.delete_requested_on == None %}
    <li role="presentation" class="{% if project_edit_page %} active {% endif %}">
      <a class="btn btn-default" href="{{ url_for('project.edit', username=project.user.username, title=project.title)}}">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        Edit
      </a>
    </li>
    <li role="presentation" class="{% if project_link_page %} active {% endif %}">
      <a class="btn btn-default"
         href="{{ url_for('project.search_and_link',
                          username=project.user.username, title=project.title)}}">
        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
        Link coprs
      </a>
    </li>
    <li role="presentation" class="{% if project_delete_page %} active {% endif %}">
      <a class="btn btn-default" href="{{ url_for('project.delete', username=project.user.username, title=project.title)}}">
        <span class="glyphicon glyphicon-erase" aria-hidden="true"></span>
        Delete
      </a>
    </li>

    <a class="btn btn-warning pull-right"
       href="{{ url_for('project.start_build', username=project.user.username, title=project.title)}}">
      <span class="glyphicon glyphicon-play" aria-hidden="true"></span>
      Run build
    </a>
    <!--<a class="btn btn-warning pull-right"-->
       <!--href="{{ url_for('project.init_repos', username=project.user.username, title=project.title)}}">-->
      <!--<span class="glyphicon glyphicon-play" aria-hidden="true"></span>-->
      <!--Create Gh &amp; Dh repos-->
    <!--</a>-->
    {% endif %}
  </ul>

  {% block project_inner_content %}{% endblock %}


{% endblock %}

src/cdic_project/cdic/templates/project/delete.html
{% extends "project/base.html" %}

{% block last_breadcrumb %}
<li>Delete</li>
{% endblock %}

{% block project_inner_content %}
  <h2 class="text-left"> Delete project </h2>

  <form class="form" method="post" role="form">
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    {{ wtf.form_field(form.mb_title) }}
     <button type="submit" class="btn btn-default btn-danger">Confirm</button>
  </form>

{% endblock %}

src/cdic_project/cdic/templates/project/details.html
{% extends "project/base.html" %}

{% block last_breadcrumb %}
<!--<li>Info</li>-->
{% endblock %}


{% block scripts %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/highlight.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/languages/dockerfile.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  {{super()}}
{% endblock %}


{% block project_inner_content %}
  {% if project.show_build_in_progress %}
  <div class="row">
    <div class="col-xs-12">
      <h4 class="text-center">
        Build is running,
        <a href="{{ url_for(
                'project.details', username=project.user.username, title=project.title) }}"
           target="_self">
          refresh
        </a>
        page to get latest state
      </h4>
      <div class="progress">
        <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
             aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">

        </div>
      </div>
    </div>
  </div>
  {% endif %}
  <br />
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <b>Configuration</b>
        </div>
        <div class="panel-body">
          <dl class="dl-horizontal">

            <dt>Linked coprs</dt>
            {% for copr in project.linked_coprs %}
              <dd>
                <a href="{{ copr.copr_url }}">
                  {{ copr.full_name }}
                </a>
              </dd>
            {% else %}
            <dd>(no linked coprs)</dd>
            {% endfor %}

            <!--<dt>Source type</dt>-->
            <!--<dd>{{ project.source_mode }}</dd>-->

            {% if project.source_mode == "git_url"  and project.git_url %}
            <dt>Git</dt>
            <dd>{{ project.git_url }}</dd>

            <dt>Dockerfile path</dt>
            <dd>{{ project.dockerfile_path|default("/") }}</dd>
            {% endif %}

            <dt>Dependent repos:</dt>
            <dd>
              {% if project.github_repo_exists %}
                <a href="{{ project.github_repo_url }}">
                  GitHub
                </a>
              {% else %}
                (not created yet)
              {% endif %}
            </dd>

            <dt>&nbsp;</dt>
            <dd>
              {% if project.dockerhub_repo_exists %}
                <a href="{{ project.dockerhub_repo_url }}">
                  DockerHub
                </a>
              {% endif %}
            </dd>


          </dl>

          {% if project.dockerhub_repo_exists %}
          <h4 class="text-center">Pull results:</h4>
          <div class="alert alert-danger" role="alert">
            Fedora doesn't provide any guaranties. Use on your own risk.
          </div>
          <div class="well">
                <code>
                  {{ project.docker_pull_snippet }}
                </code>
            </div>
          {% endif %}

        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <b>Activity log</b>
        </div>
        <div class="panel-body">
          <dl class="dl-horizontal">
            {% for event in  project.recent_events.limit(10).all() %}
              <dt>{{ event.created_on | time_ago}}: </dt>
              <dd>{{ event.human_text }} </dd>
            {% endfor %}


          </dl>
        </div>
      </div>
    </div>

    <div class="col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <b>Dockerfile preview</b>
        </div>
        <div class="panel-body">
          <pre><code class="dockerfile">{{ project.patched_dockerfile }}</code></pre>
        </div>
      </div>

    </div>

  </div>


{% endblock %}

src/cdic_project/cdic/templates/project/edit.html
{% extends "project/base.html" %}

{% block last_breadcrumb %}
<li>Edit</li>
{% endblock %}

{% block project_inner_content %}
  <h2 class="text-left"> Editing project </h2>
  <p class="pull-right">
    <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
    <a href="https://docs.docker.com/reference/builder/"  target="_blank">
      Dockerfile format reference
    </a>
  </p>

  <form class="form" method="post" role="form">
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <input type="hidden" name="title" value="{{ project.title }}" />

    {% if project.source_mode == "local_text" %}
      {{ wtf.form_field(form.local_text,rows=20) }}
    {% endif %}

    {% if project.source_mode == "git_url" %}
      {{ wtf.form_field(form.git_url) }}
    {% endif %}


     <button type="submit" class="btn btn-default">Submit</button>
  </form>

{% endblock %}

src/cdic_project/cdic/templates/project/find_and_link_coprs.html
{% extends "project/base.html" %}

{% block last_breadcrumb %}
<li>Link coprs</li>
{% endblock %}

{% block project_inner_content %}

  <h2 class="text-left"> Linking coprs to project</h2>

  <div class="row">
    <div class="col-xs-12 col-md-8">
      <form class="form form-inline" method="post" role="form">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>Directly enter copr project</h3>
        </div>
        <div class="panel-body">

            {{ form_add.hidden_tag() }}
            {{ wtf.form_errors(form_add, hiddens="only") }}

            {{ wtf.form_field(form_add.copr_name) }}

            <button type="submit" class="btn btn-default" name="btn" value="add_by_name">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              Add
            </button>


        </div>
      </div>
      </form>
      <hr />
      <form class="form form-horizontal" method="post" role="form">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3>Search copr project</h3>
          </div>
          <div class="panel-body">


            {{ form_search.hidden_tag() }}
            {{ wtf.form_errors(form_search, hiddens="only") }}


            <div class="input-group">
              {{ form_search.query(class='form-control') }}
              <span class="input-group-btn">
                <button type="submit" class="btn btn-default" name="btn" value="search">
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                  Search
                </button>
              </span>

            </div>
            {% if search_error %}
              <span class="label label-info">{{ search_error }}</span>
            {% endif %}
          </div>

          <ul class="list-group">
          {% for copr in  search_results %}
            <li class="list-group-item" >
              <button type="submit" class="btn btn-default btn-sm"
                      name="btn-search-add" value="{{ copr.username }}/{{ copr.projectname }}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Add
              </button>

              <a href="{{ copr.copr_url }}">
                <b>{{ copr.username }}/{{ copr.projectname }} </b>
              </a>

              <small> {{ copr.description }}</small>
            </li>
          {% endfor %}
          </ul>
        </div>
      </form>

    </div>


    <div class="col-xs-12 col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
            Enabled coprs
        </div>
        <div class="panel-body">
          <ul class="list-group">
          {% for copr_link in project.linked_coprs %}
            <li class="list-group-item">
              <a href="{{ copr_link.copr_url }}">
                {{ copr_link.full_name }}
              </a>
              <a class="pull-right btn btn-danger btn-xs"
                 href="{{ url_for('project.unlink',
                                   username=project.user.username, title=project.title, link_id=copr_link.id) }}">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                Unlink
              </a>
            </li>
          {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

src/cdic_project/cdic/templates/project/list.html
{% extends "base.html" %}

{% block inner_content %}
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li>
    <a class="active" href="{{ url_for('project.list_by_user',username=owner.username) }}">
      {{ owner.username }}
    </a>
  </li>
</ol>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Projects by: {{ owner.username }}
      {% if owner==g.user %}
        <div class="pull-right">
          <a class="btn btn-primary" href="{{ url_for('project.create_view')}}">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            Add new project
          </a>
        </div>

      {% endif %}
    </h3>

  </div>
  <div class="panel-body">

    {% for project in project_list %}
    <div class="panel panel-default">
      <div class="panel-body">
        <h3>
          <a href="{{ url_for('project.details', username=project.user.username, title=project.title) }}">
            {{ project.title }}
          </a>

          {% if project.delete_requested_on == None %}
          <span class="pull-right">
            <div class="btn-group" role="group" aria-label="...">
              {% if g.user == project.user%}
                <a href="{{ url_for('project.edit', username=project.user.username, title=project.title)}}"
                   class="btn btn-default">
                  Edit
                </a>

                {% if project.is_runnable %}
                <a class="btn btn-warning"
                   href="{{ url_for('project.start_build', username=project.user.username, title=project.title)}}">
                  Run build
                </a>
                {% endif %}
              {% endif %}

              {% if project.dockerhub_repo_exists %}
                <a href="{{ project.url_to_hub }}" class="btn btn-default">
                  Go to the Hub
                </a>
              {% endif %}
            </div>
          </span>
          {% else %}
          <span class="pull-right label label-danger">
            deleting ...
          </span>
          {% endif %}
        </h3>
      </div>
    </div>
    {% else %}

      No projects defined yet

    {% endfor %}
  </div>
</div>





{% endblock inner_content %}